# Generated by Django 5.0 on 2023-12-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='producto',
            new_name='item',
        ),
    ]
