# Generated by Django 5.0 on 2023-12-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_producto_categoria_remove_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='item',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
